dbt_demo_project:
  outputs:
    dev:
      dataset: dbt_jaffle
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us
      method: oauth
      priority: interactive
      project: # GCP project id
      threads: 1
      type: bigquery
  target: dev